# Generated by Django 3.2.2 on 2023-07-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_App', '0004_auto_20230726_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='rent_days',
        ),
        migrations.AddField(
            model_name='car',
            name='rent_days',
            field=models.IntegerField(default=0),
        ),
    ]
