# Generated by Django 4.2.1 on 2023-07-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_App', '0005_auto_20230726_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='bookmarked',
            field=models.ManyToManyField(related_name='bookmarked', to='Solo_App.user'),
        ),
    ]
